application: order-plus
version: argeweb
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10d"

builtins:
- appstats: on
- deferred: on
- remote_api: off

inbound_services:
- mail

includes:
- application/include.yaml

handlers:
- url: /(.*?).manifest
  static_files: static/\1.manifest
  upload: static/(.*?).manifest
  mime_type: text/cache-manifest

- url: /(.*?).appcache
  static_files: static/\1.appcache
  upload: static/(.*?).appcache
  mime_type: text/cache-manifest

- url: /manifest-3.json
  static_files: static/manifest.json
  upload: static/manifest.json

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(.+\.(otf|eot|svg|ttf|woff))$
  static_files: \1
  upload: (.+\.(otf|eot|svg|ttf|woff))
  mime_type: application/octet-stream
  secure: always

- url: /static/(.+\.(less|scss|sass))$
  static_files: static\1
  upload: static/(.+\.(less|scss|sass))
  mime_type: text/css
  secure: always

- url: /static/(.+\.(json))$
  static_files: static\1
  upload: static/(.+\.(json))
  mime_type: application/json
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static/(.+\.(map))$
  static_files: static\1
  upload: static/(.+\.(map))
  mime_type: application/octet-stream
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /plugins/(.*?)/static/(.*)
  static_files: plugins/\1/static/\2
  upload: plugins/(.*?)/static/(.*)
  secure: always

- url: /img
  static_dir: static/img
  secure: always

- url: /images
  static_dir: static/images
  secure: always

- url: /swf
  static_dir: static/swf
  secure: always

- url: /fonts
  static_dir: static/fonts
  secure: always

- url: /css
  static_dir: static/css
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /js
  static_dir: static/js
  secure: always
  mime_type: text/css
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static
  static_dir: static
  secure: always

- url: /_ah/queue/deferred
  script: argeweb.deferred_app.app
  secure: always
  login: admin

- url: /.*
  script: argeweb.application.instance
  secure: always

libraries:
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: lxml
  version: latest
#- name: ssl
#  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/gae_config/.*$
- ^(.*/)?.*/.git/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.php$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.fla$
- ^(.*/)?.*\.rm$
- ^(.*/)?README$
- ^(.*/)?.idea*~$
- ^(.*/)?.*\.py___jb_bak___$
- ^(.*/)?.*\.py___jb_old___$