module: default
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10d"

builtins:
- appstats: on
- deferred: on
- remote_api: off

inbound_services:
- mail

includes:
- plugins/user_file/include.yaml

handlers:
- url: /(.*?).manifest
  static_files: static/\1.manifest
  upload: static/(.*?).manifest
  mime_type: text/cache-manifest

- url: /(.*?).appcache
  static_files: static/\1.appcache
  upload: static/(.*?).appcache
  mime_type: text/cache-manifest

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /assets/(themes|plugins|application)/(.*?)/static/(.+\.(js|css))$
  script: plugins.code.getcode

- url: /assets/(themes|plugins|application)/(.*?)/static/(.+\.(gif|jpg|jpeg|png|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss))$
  script: plugins.file.getfile

- url: /r/(themes|plugins|application)/(.*?)/(.+\.(js|css|gif|jpg|jpeg|png|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(js|css|gif|jpg|jpeg|png|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss))

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(woff))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(woff))
  mime_type: application/font-woff

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(woff2))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(woff2))
  mime_type: application/font-woff2

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(svg))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(svg))
  mime_type: image/svg+xml

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(eot))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(eot))
  mime_type: application/vnd.ms-fontobject

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(ttf))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(ttf))
  mime_type: application/octet-stream

- url: /(themes|plugins|application)/(.*?)/static/(.+\.(json))
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.+\.(json))
  mime_type: application/json

- url: /(themes|plugins|application)/(.*?)/static/(.*)
  static_files: \1/\2/static/\3
  upload: (themes|plugins|application)/(.*?)/static/(.*)

- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: argeweb.deferred_app.app
  login: admin

#- url: /assets/files
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always
#
#- url: /assets/files/
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always

- url: /webdav
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /webdav/
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /webdav/.*
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /(.+\.(js|css))$
  script: plugins.code.getcode

- url: /(.+\.(gif|jpg|jpeg|png|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss))$
  script: plugins.file.getfile

- url: /.*
  script: argeweb.application.instance

libraries:
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: lxml
  version: latest
#ssl

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/gae_config/.*$
- ^(.*/)?.*static/bower_components/.*$
- ^(.*/)?.*static/node_modules/.*$
- ^(.*/)?.*argeweb/manage/.*$
- ^(.*/)?.*/.git/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.php$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.exe$
- ^(.*/)?.*\.dll$
- ^(.*/)?.*\.pyd$
- ^(.*/)?.*\.fla$
- ^(.*/)?.*\.rm$
- ^(.*/)?README$
- ^(.*/)?.idea*~$
- ^(.*/)?.*\.py___jb_bak___$
- ^(.*/)?.*\.py___jb_old___$
