module: default
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10d"

#basic_scaling:
#  max_instances: 1
#  idle_timeout: 30m

#automatic_scaling

builtins:
- appstats: on
- deferred: on
- remote_api: off

inbound_services:
- mail

includes:
- plugins/user_file/include.yaml

handlers:
- url: /(themes|plugins|application)/(.*?)/(.+\.(pdf))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(pdf))
  mime_type: application/octet-stream

- url: /(themes|plugins|application)/(.*?)/(.+\.(woff))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(woff))
  mime_type: application/font-woff

- url: /(themes|plugins|application)/(.*?)/(.+\.(woff2))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(woff2))
  mime_type: application/font-woff2

- url: /(themes|plugins|application)/(.*?)/(.+\.(svg))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(svg))
  mime_type: image/svg+xml

- url: /(themes|plugins|application)/(.*?)/(.+\.(eot))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(eot))
  mime_type: application/vnd.ms-fontobject

- url: /(themes|plugins|application)/(.*?)/(.+\.(ttf))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(ttf))
  mime_type: application/octet-stream

- url: /(themes|plugins|application)/(.*?)/(.+\.(json))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(json))
  mime_type: application/json

- url: /(themes|plugins|application)/(.*?)/(.+\.(js))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(js))
  mime_type: text/javascript

- url: /(themes|plugins|application)/(.*?)/(.+\.(css|less|sass|scss))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(css|less|sass|scss))
  mime_type: text/css

- url: /(themes|plugins|application)/(.*?)/(.+\.(jpg|jpeg))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(jpg|jpeg))
  mime_type: image/jpeg

- url: /(themes|plugins|application)/(.*?)/(.+\.(png))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(png))
  mime_type: image/png

- url: /(themes|plugins|application)/(.*?)/(.+\.(ico|icon))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(ico|icon))
  mime_type: image/x-icon

- url: /(themes|plugins|application)/(.*?)/(.+\.(gif))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(gif))
  mime_type: image/gif

- url: /r/(themes|plugins|application)/(.*?)/(.+\.(js|css|gif|jpg|jpeg|ico|icon|png|swf|avi|mpeg|mp4|less|sass|scss))
  static_files: \1/\2/\3
  upload: (themes|plugins|application)/(.*?)/(.+\.(js|css|gif|jpg|jpeg|ico|icon|png|swf|avi|mpeg|mp4|less|sass|scss))

- url: /(static)/(.*?)/(.+\.(eot))
  static_files: \1/\2/\3
  upload: (static)/(.*?)/(.+\.(eot))
  mime_type: application/vnd.ms-fontobject

- url: /(static)/(.*?)/(.+\.(otf))
  static_files: \1/\2/\3
  upload: (static)/(.*?)/(.+\.(otf))
  mime_type: application/font-otf

- url: /(static)/(.*?)(.+\.(json))
  static_files: \1/\2\3
  upload: (static)/(.*?)(.+\.(json))
  mime_type: application/javascript

- url: /(static)/(.*?)(.+\.(map))
  static_files: \1/\2\3
  upload: (static)/(.*?)(.+\.(map))
  mime_type: application/octet-stream

- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: argeweb.deferred_app.app
  login: admin

#- url: /assets/files
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always
#
#- url: /assets/files/
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always

- url: /webdav
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /webdav/
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /webdav/.*
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /assets/(.+\.(js|css))$
  script: plugins.code.getcode
  secure: always

- url: /assets/(.+\.(gif|jpg|jpeg|png|ico|icon|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss|pdf|zip))$
  script: plugins.file.getfile
  secure: always

- url: /(.+\.(js|css))$
  script: plugins.code.getcode
  secure: always

- url: /(.+\.(gif|jpg|jpeg|png|ico|icon|woff|woff2|swf|eot|svg|ttf|avi|mpeg|mp4|less|scss|pdf|zip))$
  script: plugins.file.getfile
  secure: always

- url: /.*
  script: argeweb.application.instance
#  secure: always
#  google app engine dev server not support https
#  you should disable secure: always option


libraries:
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: lxml
  version: latest
#ssl

skip_files:
- ^temp_deploy.yaml$
- ^manage.py$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/gae_config/.*$
- ^(.*/)?.*static/bower_components/.*$
- ^(.*/)?.*static/node_modules/.*$
- ^(.*/)?.*manage/.*$
- ^(.*/)?.*/.git/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.php$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.exe$
- ^(.*/)?.*\.dll$
- ^(.*/)?.*\.pyd$
- ^(.*/)?.*\.fla$
- ^(.*/)?.*\.rm$
- ^(.*/)?README$
- ^(.*/)?.idea*~$
- ^(.*/)?.*\.py___jb_bak___$
- ^(.*/)?.*\.py___jb_old___$
- ^(.*/)bower_path.json$
- ^(.*/)bower.json$
- ^(.*/)desktop.ini$
- ^(.*/).dropbox$
