module: default
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10d"

builtins:
- appstats: on
- deferred: on
- remote_api: off

inbound_services:
- mail

includes:
- plugins/user_file/include.yaml

handlers:
- url: /(.*?).manifest
  static_files: static/\1.manifest
  upload: static/(.*?).manifest
  mime_type: text/cache-manifest

- url: /(.*?).appcache
  static_files: static/\1.appcache
  upload: static/(.*?).appcache
  mime_type: text/cache-manifest

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /themes/(.*?)/static/(.*)
  static_files: themes/\1/static/\2
  upload: themes/(.*?)/static/(.*)
  secure: always

- url: /plugins/(.*?)/static/(.*)
  static_files: plugins/\1/static/\2
  upload: plugins/(.*?)/static/(.*)
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /_ah/queue/deferred
  script: argeweb.deferred_app.app
  secure: always
  login: admin

#- url: /assets/files
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always
#
#- url: /assets/files/
#  script: plugins.webdav.webdav_application.web_dav
#  secure: always

- url: /(.+\.(js|css))$
  script: plugins.code.getfile_app

- url: /assets/files/.*
  script: plugins.webdav.webdav_application.web_dav
  secure: always

- url: /.*
  script: argeweb.application.instance
  secure: always

libraries:
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: lxml
  version: latest
#ssl

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/gae_config/.*$
- ^(.*/)?.*/.git/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.php$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.fla$
- ^(.*/)?.*\.rm$
- ^(.*/)?README$
- ^(.*/)?.idea*~$
- ^(.*/)?.*\.py___jb_bak___$
- ^(.*/)?.*\.py___jb_old___$
